# Generated by Django 4.2.4 on 2023-08-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_picture_name_alter_picture_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='name',
            field=models.CharField(default='unnamed', max_length=30),
        ),
    ]
