# Generated by Django 4.2.4 on 2023-08-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_question_already_asked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(choices=[('GE', 'Geography'), ('EN', 'Entertainment'), ('HI', 'History'), ('AL', 'Art and Literature'), ('ST', 'Science and Technology'), ('SP', 'Sports and Pleasure')], max_length=2, null=True),
        ),
    ]
