# Generated by Django 4.2.4 on 2023-08-29 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_statistics_answered_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='answered_questions',
        ),
    ]
