# Generated by Django 4.2.4 on 2023-08-29 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_remove_statistics_answered_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
