# Generated by Django 4.2.4 on 2023-08-29 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_picture_created_on_picture_modified_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='modified_on',
        ),
    ]
