# Generated by Django 4.2.4 on 2023-08-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_basicanswer_created_at_basicanswer_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='questions_answered_counter',
            field=models.IntegerField(default=0),
        ),
    ]
