# Generated by Django 4.2.4 on 2023-08-30 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_round_questions_answered_counter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='questions_answered_counter',
            new_name='answered_questions_counter',
        ),
    ]
