# Generated by Django 4.2.4 on 2023-08-30 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_statistic_delete_statistics_round_statistic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='answered_questions_counter',
        ),
    ]
