# Generated by Django 4.2.4 on 2023-08-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_remove_round_answered_questions_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicanswer',
            name='explanation',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.DeleteModel(
            name='TruthAnswer',
        ),
    ]
