# Generated by Django 4.2.4 on 2023-08-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_basicanswer_explanation_delete_truthanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicanswer',
            name='answer_text',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
